apiVersion: v1
kind: Service
metadata:
  name: postgres-service  # DNS name
spec:
  type: ClusterIP # Only accessible inside the cluster
  selector:
    component: postgres # send traffic to pods with this label
  ports:
    - port: 5432  # Service port (internal cluster port)
      targetPort: 5432 # Container port in the pod