apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: ClusterIP # Only accessible inside the cluster
  selector:
    component: server # send traffic to pods with this label
  ports:
    - port: 8000  # Service port (internal cluster port)
      targetPort: 8000 # Container port in the pod