apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-deployment-scaler-role
  namespace: default
rules:
  - apiGroups: ["apps"] 
    resources: ["deployments"]
    verbs: ["get", "update", "patch", "list", "watch"]