apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaler-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: server-scaler-sa
    namespace: default
roleRef:
  kind: Role
  name: server-deployment-scaler-role
  apiGroup: rbac.authorization.k8s.io